version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: attbancojava
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bancoaulajava
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"