version: '3.8'

services:
  image: mysql:8.0
  container_name: attbancojava
  environment:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: bancoaulajava
    MYSQL_USER: usuario
    MYSQL_PASSWORD: senha123
  ports:
    - 